name: Basic Benchmark
on: [push, pull_request]

jobs:
  basic_benchmark:
    name: Basic Benchmark
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
    steps:
      - uses: ros-tooling/setup-ros@v0.7
      - name: checkout
        uses: actions/checkout@v4
#        with:
#          path: ros_ws/src
      - name: run benchmark
        run: bash run_benchmarks.sh